### ISSUE TITLE
Subscriptions/ Recurring payments 

### ISSUE THREAD

**Issue by DejiAwoniyi** [just1and0/React-Native-Paystack-WebView#59]
I am currently using and enjoying Paystack's react native PaystackWebView component. This works seamlessly for accepting singular payments. 

Having browsed through the Paystack Docs, I see that recurring payments and Subscriptions are possible. Is there a way to integrate this into PaystackWebView on react native? The documentation was not quite clear on this.

Thanks

**Comment by mosoakinyemi** [comment]
Will look into this

**Comment by mosesegboh** [comment]
Hello, installed the library, but I cannot find  the "Pay Now" button when I run the component on my app. Who can help please.

**Comment by just1and0** [comment]
> Hello, installed the library, but I cannot find the "Pay Now" button when I run the component on my app. Who can help please.

Hey 👋🏾

You should make this a new issue and not a comment on another unrelated issue.

thanks 🙂

**Comment by just1and0** [comment]
Hey @DejiAwoniyi 

Subscription/Recurring payment was once supported in [V3.1.9 ](https://www.npmjs.com/package/react-native-paystack-webview/v/3.1.9) but was removed because of security issues. Being able to perform Subscription/Recurring payment means you'd be exposing your paystack secret key and that's not safe as just about anyone with enough time to spare could easily get your secret key and perform unauthorised transactions.

I'll suggest you handle such transaction on the backend 🙂 I know, I know, more work 🥴 but totally worth it for the product and your peace of mind 😊
