### ISSUE TITLE
Shows blank white screen when I close the modal from the X button

### ISSUE THREAD

**Issue by PrincewillIroka** [just1and0/React-Native-Paystack-WebView#6]
This library is awesome, but I'm facing a little challenge with going back to the app after closing the Paystack Interface (WebView) from the X button. When I click the X button, the WebView closes, but the app shows a blank white screen. I always have to close the app and open it again at this point.

**Comment by just1and0** [comment]
Hey @PrincewillIroka,

I honestly don't understand your issue, could you maybe share a screen record so i best understand the issue. Also what version of react native are you using ?

**Comment by PrincewillIroka** [comment]
@just1and0 Thanks for the prompt response. I've attached a screen record of the issue to this comment. And I'm using react-native 0.59.8
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26362657/72802677-9ac4ef00-3c4c-11ea-81f9-ae709119aaaf.gif)

**Comment by okechukwu0127** [comment]
I am stock on the white screen too when i click on the Cancel button and when i complete a payment. 

I have a feeling that the WebView property **onMessage** is not been triggered, thus it stuck since  the state showModal remains true
I am using "react-native": "0.59.8".

How can i resolve this issue of white screen ?

**Comment by okechukwu0127** [comment]
I was able to solve the entire issue for this plugin after some research.

PROBLEM 1 => PACKAGE GETS STUCK ON WHITE SCREEN
The season for the white screen is because the WebView does not send a message to the RN app so the app ends up been stock on the Model true visibility state.

SOLUTION
After WebView v.5, the syntax for sending data from WebView changed and the application seems to be using the old syntax which would not work anymore

Locate plugin index file at
node_modules\react-native-paystack-webview\index.js

change => postMessage(JSON.stringify(resp))
to =>  window.ReactNativeWebView.postMessage(JSON.stringify(resp))

Do this for both the   callback: function(response) &  on the  onClose: function().
Once this is done, the app would no lonnger be stock on the white screen.

My app runs on the following versions
"react-native-webview": "^8.1.0",
"react-native": "0.59.8",
"react": "16.8.3",

PROBLEM 2 => PPAYMENT GETWAY WEBVIEW CONTENT IS TOO TINY

SOLUTION 

Solving this is very easy.
All you need to do is add the following line of code to your head tag within the plugin

Locate plugin index file at
node_modules\react-native-paystack-webview\index.js

add this code on the head tag
<meta name="viewport" content="width=device-width, initial-scale=1.0">



so try this and THANK ME LATER
Best of luck

**Comment by just1and0** [comment]
Thanks, @okechukwu0127! seems you've cracked this one!

I'm currently running a test on the PR you sent, once I'm done I guess I can close this issue by tonight.
Really grateful you could help out and reduce my work 😅

I have been working on some cool stuff for a new release to support react-native version 0.60>, if you'd like to be a maintainer I won't mind letting you in while we build cool stuff 😏

again thanks!

**Comment by okechukwu0127** [comment]
@just1and0 thats not a problem at all.
I would always be willing to assist at my spear time.

Regards

**Comment by deveid** [comment]
> I was able to solve the entire issue for this plugin after some research.
> 
> PROBLEM 1 => PACKAGE GETS STUCK ON WHITE SCREEN
> The reason for the white screen is because the WebView does not send a message to the RN app successfully so the app ends up been stock on the Model true visibility state.
> 
> SOLUTION
> After WebView v.5, the syntax for sending data from WebView changed and the application seems to be using the old syntax which would not work anymore
> 
> Locate plugin index file at
> node_modules\react-native-paystack-webview\index.js
> 
> change => postMessage(JSON.stringify(resp))
> to => window.ReactNativeWebView.postMessage(JSON.stringify(resp))
> 
> Do this for both the callback: function(response) & on the onClose: function().
> Once this is done, the app would no lonnger be stock on the white screen.
> 
> My app runs on the following versions
> "react-native-webview": "^8.1.0",
> "react-native": "0.59.8",
> "react": "16.8.3",
> 
> PROBLEM 2 => PPAYMENT GETWAY WEBVIEW CONTENT IS TOO TINY
> 
> SOLUTION
> 
> Solving this is very easy.
> All you need to do is add the following line of code to your head tag within the plugin
> 
> Locate plugin index file at
> node_modules\react-native-paystack-webview\index.js
> 
> add this code on the head tag
> so try this and THANK ME LATER
> Best of luck

Which code should be written for the tiny webpageview?

**Comment by just1and0** [comment]
@deveid I don't understand the question.

**Comment by deveid** [comment]
@just1and0 The payment gateway is tiny, so I was asking how do I magnify it without having to zoom in

**Comment by just1and0** [comment]
hey, this issue has been resolved,  try upgrading the package version to the latest! that should do it 😊

**Comment by deveid** [comment]
I'm using version 2.0.2 and its tiny except when zoomed in

**Comment by okechukwu0127** [comment]
> I'm using version 2.0.2 and its tiny except when zoomed in

Add this code to the head tag =>

                      <meta name="viewport" content="width=device-width, initial-scale=1.0">
